// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB {
    public partial class CompanyRoot
    {
        public string RComID { get; set; }
        public string StartComID { get; set; }
        public string RComName { get; set; }
        public string ImageThumb { get; set; }
        public string ImageFull { get; set; }
        public string ImageBackGround { get; set; }
        public bool IsActive { get; set; }
    }
}