// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB {

    public partial class ItemBarcode
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string ItemID { get; set; }
        public string Barcode { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public bool IsActive { get; set; }
    }
}