// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB {
    public partial class vw_UserInfoMini
    {
        public string Username { get; set; }
        public string EmpCode { get; set; }
        public string FullName { get; set; }
        public string FullName_En { get; set; }
    }
}