// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.FILEDB.TT
{
    public partial class XFiles
    {
        public int ID { get; set; }
        public string AppID { get; set; }
        /// <summary>
        /// ใช้อ้างอิงกับ Table : DocFileData มาจาก RefTableSource+&quot;-&quot;+KeyRefID
        /// </summary>
        public string FileID { get; set; }
        public string FileName { get; set; }
        /// <summary>
        /// IMG / FILE
        /// </summary>
        public string FileType { get; set; }
        public string FileExt { get; set; }
        public string FilePath { get; set; }
        public string OriginFileName { get; set; }
        public string OriginFileExt { get; set; }
        public string OriginFilePath { get; set; }
        public byte[] Data { get; set; }
        public byte[] DataThumb { get; set; }
        public string DataInBase64 { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}