// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RobotWasm.Server.XFFKK
{
    public partial class cimsContext : DbContext
    {
        public cimsContext()
        {
        }

        public cimsContext(DbContextOptions<cimsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<custom_board_in_user> custom_board_in_user { get; set; }
        public virtual DbSet<custom_widget> custom_widget { get; set; }
        public virtual DbSet<custom_widget_in_user> custom_widget_in_user { get; set; }
        public virtual DbSet<custom_widget_param_in_user> custom_widget_param_in_user { get; set; }
        public virtual DbSet<custom_widget_param_master> custom_widget_param_master { get; set; }
        public virtual DbSet<vw_custom_board_in_user> vw_custom_board_in_user { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<custom_board_in_user>(entity =>
            {
                entity.Property(e => e.board_desc).HasMaxLength(255);

                entity.Property(e => e.board_id).HasMaxLength(255);

                entity.Property(e => e.board_name).HasMaxLength(255);

                entity.Property(e => e.board_type).HasMaxLength(255);

                entity.Property(e => e.created_by).HasMaxLength(255);

                entity.Property(e => e.created_date).HasColumnType("timestamp without time zone");

                entity.Property(e => e.modified_by).HasMaxLength(255);

                entity.Property(e => e.modified_date).HasColumnType("timestamp without time zone");

                entity.Property(e => e.username).HasMaxLength(255);
            });

            modelBuilder.Entity<custom_widget>(entity =>
            {
                entity.Property(e => e.widget_desc).HasMaxLength(255);

                entity.Property(e => e.widget_id).HasMaxLength(255);
            });

            modelBuilder.Entity<custom_widget_in_user>(entity =>
            {
                entity.Property(e => e.board_id).HasMaxLength(255);

                entity.Property(e => e.orientation).HasMaxLength(10);

                entity.Property(e => e.username).HasMaxLength(255);

                entity.Property(e => e.widget_id).HasMaxLength(255);
            });

            modelBuilder.Entity<custom_widget_param_in_user>(entity =>
            {
                entity.Property(e => e.data).HasMaxLength(1000);

                entity.Property(e => e.data_type).HasMaxLength(255);

                entity.Property(e => e.param_id).HasMaxLength(255);

                entity.Property(e => e.username).HasMaxLength(255);
            });

            modelBuilder.Entity<custom_widget_param_master>(entity =>
            {
                entity.Property(e => e.data).HasMaxLength(1000);

                entity.Property(e => e.data_type).HasMaxLength(255);

                entity.Property(e => e.param_id).HasMaxLength(255);

                entity.Property(e => e.param_name).HasMaxLength(255);

                entity.Property(e => e.widget_id).HasMaxLength(255);
            });

            modelBuilder.Entity<vw_custom_board_in_user>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vw_custom_board_in_user");

                entity.Property(e => e.board_desc).HasMaxLength(255);

                entity.Property(e => e.board_id).HasMaxLength(255);

                entity.Property(e => e.board_name).HasMaxLength(255);

                entity.Property(e => e.board_type).HasMaxLength(255);

                entity.Property(e => e.username).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}