// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Collections;

namespace Robot.Data.CIMSDB
{
    public partial class api_param_res
    {
        public int id { get; set; }
        public string api_id { get; set; }
        public string param_type { get; set; }
        public string field_id { get; set; }
        public string data_type { get; set; }
        public string description { get; set; }
        public int sort { get; set; }
        public int is_require { get; set; }
    }
}