// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.XFilesCenterDB.TT {
    public partial class xfiles_ref
    {
        public int id { get; set; }
        public string file_id { get; set; }
        public string? loc_id { get; set; }
        public string? owner_id { get; set; }
        public string? rcom_id { get; set; }
        public string? com_id { get; set; }
        public string app_id { get; set; }
        public string? doc_id { get; set; }
        public int? doc_linenum { get; set; }
        public string? source_table { get; set; }
        public string file_type { get; set; }
        public string? doc_type { get; set; }
        public string? doc_cate { get; set; }
        public string? remark { get; set; }
     public DateTime? upload_completed_time { get; set; }
        public string? created_by { get; set; }
        public DateTime? created_date { get; set; }
        public string? modified_by { get; set; }
        public DateTime? modified_date { get; set; }
        public bool? is_active { get; set; }
    }
}