// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public class PromotionPattern {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string PatternID { get; set; }
        public string PatternDesc { get; set; }
        public bool? IsActive { get; set; }
    }

}