// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public partial class UploadLog
    {
        public int ID { get; set; }
        public string UPloadID { get; set; }
        public DateTime UploadDate { get; set; }
        public string UploadResult { get; set; }
        public string Message { get; set; }
        public string FucnID { get; set; }
        public string AppID { get; set; }
    }
}