// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace RobotWasm.Shared.Data.DimsDB {
    public partial class api_cate {
        public int id { get; set; }
        public string cate_id { get; set; }
        public string cate_name { get; set; }
        public int sort { get; set; }
        public int is_active { get; set; }
        public string img_path { get; set; }
        public string page { get; set; }
    }
}