// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class company_group_info
    {
        public int id { get; set; }
        public string company_groupid { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public DateTime? created_date { get; set; }
        public string created_by { get; set; }
        public DateTime? modified_date { get; set; }
        public string modified_by { get; set; }
        public short? is_active { get; set; }
    }
}