// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class master_type_line
    {
        public int id { get; set; }
        public string master_type_id { get; set; }
        public string master_type_name { get; set; }
        public string value_txt { get; set; }
        public decimal? value_num { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public int? sort { get; set; }
        public int? is_active { get; set; }
    }
}