// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class master_type_head
    {
        public int id { get; set; }
        public string master_type_id { get; set; }
        public string master_type_name { get; set; }
        public string remark { get; set; }
        public int? user_create { get; set; }
        public int? is_active { get; set; }
    }
}