// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class news_info {
        public int id { get; set; }
        public string newid { get; set; }
        public string title { get; set; }
        public DateTime? newdate { get; set; }
        public string desc { get; set; }
        public int? is_active { get; set; }
    }
}