// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class vw_doc_head
    {
        public int? id { get; set; }
        public string doc_id { get; set; }
        public string doc_desc { get; set; }
        public string doc_remark { get; set; }
        public string doc_type_id { get; set; }
        public string doc_cate_id { get; set; }
        public DateTime? publish_date { get; set; }
        public int? is_publish { get; set; }
        public DateTime? created_date { get; set; }
        public string created_by { get; set; }
        public DateTime? modified_date { get; set; }
        public string modified_by { get; set; }
        public int? count_file { get; set; }
        public int? is_active { get; set; }
    }
}