// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB
{
    public partial class vw_permission_group_in_menu
    {
        public long? rowkey { get; set; }
        public string group_id { get; set; }
        public string group_name { get; set; }
        public string group_description { get; set; }
        public string menu_id { get; set; }
        public string menu_code { get; set; }
        public string menu_name { get; set; }
        public string menu_description1 { get; set; }
        public string menu_description2 { get; set; }
        public short? group_sort { get; set; }
        public string url { get; set; }
        public string icon { get; set; }
        public int? is_open { get; set; }
        public int? need_open { get; set; }
        public int? is_create { get; set; }
        public int? need_create { get; set; }
        public int? is_edit { get; set; }
        public int? need_edit { get; set; }
        public int? is_delete { get; set; }
        public int? need_delete { get; set; }
        public int? is_print { get; set; }
        public int? need_print { get; set; }
        public int? is_active { get; set; }
    }
}