//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data.FileStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class XFiles
    {
        public int ID { get; set; }
        public string AppID { get; set; }
        public string FileID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FileExt { get; set; }
        public string FilePath { get; set; }
        public string OriginFileName { get; set; }
        public string OriginFileExt { get; set; }
        public string OriginFilePath { get; set; }
        public byte[] Data { get; set; }
        public byte[] DataThumb { get; set; }
        public string DataInBase64 { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
