// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.DPMNEW.TT {
    public partial class DPM_NewsCateKeywordLine
    {
        public int ID { get; set; }
        public string CateID { get; set; }
        public string KeyWord { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}