// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RobotAPI.XXWWECC
{
    public partial class DPMQContext : DbContext
    {
        public DPMQContext()
        {
        }

        public DPMQContext(DbContextOptions<DPMQContext> options)
            : base(options)
        {
        }

        public virtual DbSet<dpm_volunteer> dpm_volunteer { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<dpm_volunteer>(entity =>
            {
                entity.ToTable("dpm_volunteer", "etl");

                entity.Property(e => e.address).HasMaxLength(255);

                entity.Property(e => e.amphur_id).HasMaxLength(255);

                entity.Property(e => e.amphur_name).HasMaxLength(255);

                entity.Property(e => e.amphur_name1).HasMaxLength(255);

                entity.Property(e => e.center_id).HasMaxLength(255);

                entity.Property(e => e.code).HasMaxLength(255);

                entity.Property(e => e.contact_address).HasMaxLength(255);

                entity.Property(e => e.contact_amphur_id).HasMaxLength(255);

                entity.Property(e => e.contact_district_id).HasMaxLength(255);

                entity.Property(e => e.contact_moo).HasMaxLength(255);

                entity.Property(e => e.contact_province_id).HasMaxLength(255);

                entity.Property(e => e.contact_road).HasMaxLength(255);

                entity.Property(e => e.contact_soi).HasMaxLength(255);

                entity.Property(e => e.contact_tel).HasMaxLength(255);

                entity.Property(e => e.district_id).HasMaxLength(255);

                entity.Property(e => e.district_name).HasMaxLength(255);

                entity.Property(e => e.district_name1).HasMaxLength(255);

                entity.Property(e => e.email).HasMaxLength(255);

                entity.Property(e => e.fax).HasMaxLength(255);

                entity.Property(e => e.latitude).HasMaxLength(255);

                entity.Property(e => e.longitude).HasMaxLength(255);

                entity.Property(e => e.name).HasMaxLength(255);

                entity.Property(e => e.prefix).HasMaxLength(255);

                entity.Property(e => e.province_id).HasMaxLength(255);

                entity.Property(e => e.province_name).HasMaxLength(255);

                entity.Property(e => e.province_name1).HasMaxLength(255);

                entity.Property(e => e.register_date).HasMaxLength(255);

                entity.Property(e => e.tel).HasMaxLength(255);

                entity.Property(e => e.type).HasMaxLength(255);

                entity.Property(e => e.vol_birth_date).HasMaxLength(255);

                entity.Property(e => e.vol_firstname).HasMaxLength(255);

                entity.Property(e => e.vol_id).HasMaxLength(255);

                entity.Property(e => e.vol_id_card).HasMaxLength(255);

                entity.Property(e => e.vol_lastname).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}