//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addr_District
    {
        public int ID { get; set; }
        public string ProvinceID { get; set; }
        public string ProvinceIDEng { get; set; }
        public string AmphoeID { get; set; }
        public string AmphoeIDEng { get; set; }
        public string DistrictID { get; set; }
        public string DistrictIDEng { get; set; }
        public string PostCode { get; set; }
        public string CountryID { get; set; }
        public string RegionID { get; set; }
        public Nullable<bool> IsMetropolis { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
