//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public string BankCode { get; set; }
        public string SwiftCode { get; set; }
        public string Name_TH { get; set; }
        public string Name_EN { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool IsActive { get; set; }
    }
}
