//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRoot
    {
        public string RComID { get; set; }
        public string RComName { get; set; }
        public string ImageThumb { get; set; }
        public string ImageFull { get; set; }
        public string ImageBackGround { get; set; }
        public bool IsActive { get; set; }
    }
}
