//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string ConfigID { get; set; }
        public string ConfigName { get; set; }
        public string ValueString1 { get; set; }
        public string ValueString2 { get; set; }
        public decimal ValueNumber1 { get; set; }
        public decimal ValueNumber2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
