//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInfo
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string ItemID { get; set; }
        public string ItemCode { get; set; }
        public string MasterItemID { get; set; }
        public string Barcode { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string GLGroupID { get; set; }
        public string RefID { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string TypeID { get; set; }
        public string CateID { get; set; }
        public string Group1ID { get; set; }
        public string Group2ID { get; set; }
        public string Group3ID { get; set; }
        public string BrandID { get; set; }
        public string SerialNumber { get; set; }
        public string PackingID { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public string PriceTaxCondType { get; set; }
        public string UnitID { get; set; }
        public string StkUnitID { get; set; }
        public decimal VolPerUOM { get; set; }
        public string VendorID { get; set; }
        public decimal Weight { get; set; }
        public decimal Dimension { get; set; }
        public string VatTypeID { get; set; }
        public bool IsKeepStock { get; set; }
        public bool IsLotItem { get; set; }
        public Nullable<bool> IsOntop { get; set; }
        public bool IsPackaging { get; set; }
        public string PackagingID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<int> Sort { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public bool IsSysData { get; set; }
        public bool IsHold { get; set; }
        public bool IsActive { get; set; }
    }
}
