//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPriceInfo
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string ItemID { get; set; }
        public string CustID { get; set; }
        public int UseLevel { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public decimal Price { get; set; }
        public string PriceTaxCondType { get; set; }
        public string RefID { get; set; }
        public string DataSource { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
