//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineLogIn
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string FromReqID { get; set; }
        public string UserType { get; set; }
        public string AppID { get; set; }
        public string LineID { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> HasAttachFIle { get; set; }
        public string ReqMemo { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedMemo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LatestLogin { get; set; }
    }
}
