//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineSender
    {
        public int ID { get; set; }
        public string SenderID { get; set; }
        public string AppID { get; set; }
        public string ApiUrl { get; set; }
        public string ReturnUrl { get; set; }
        public string Secret { get; set; }
        public string Token { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
    }
}
