//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id { get; set; }
        public string LinkType { get; set; }
        public string LinkName { get; set; }
        public string BaseUrl { get; set; }
        public string AppLink { get; set; }
        public string Port { get; set; }
        public string VirtualPath { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string Token { get; set; }
        public string Domain { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string AuthenType { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
