//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTypeLine
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string MasterTypeID { get; set; }
        public string ValueTXT { get; set; }
        public decimal ValueNUM { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public int Sort { get; set; }
        public string ParentID { get; set; }
        public string ParentValue { get; set; }
        public string RefID { get; set; }
        public Nullable<bool> IsSysData { get; set; }
        public bool IsActive { get; set; }
    }
}
