//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OINVLine
    {
        public int ID { get; set; }
        public string SOINVID { get; set; }
        public int LineNum { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string DocTypeID { get; set; }
        public System.DateTime SOINVDate { get; set; }
        public string RefDocID { get; set; }
        public int RefDocLineNum { get; set; }
        public string CustomerID { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemTypeID { get; set; }
        public string ItemCateID { get; set; }
        public string ItemGroupID { get; set; }
        public string ItemAccGroupID { get; set; }
        public bool IsStockItem { get; set; }
        public decimal Weight { get; set; }
        public string WUnit { get; set; }
        public decimal QtyOrder { get; set; }
        public decimal QtyShip { get; set; }
        public decimal QtyInvoice { get; set; }
        public decimal QtyReturn { get; set; }
        public string Unit { get; set; }
        public string Packaging { get; set; }
        public decimal Price { get; set; }
        public decimal PriceIncVat { get; set; }
        public decimal BaseTotalAmt { get; set; }
        public decimal TotalAmt { get; set; }
        public decimal VatAmt { get; set; }
        public decimal TotalAmtIncVat { get; set; }
        public decimal VatRate { get; set; }
        public string VatTypeID { get; set; }
        public decimal OntopDiscAmt { get; set; }
        public decimal OntopDiscPer { get; set; }
        public decimal DiscPer { get; set; }
        public decimal DiscAmt { get; set; }
        public string DiscCalBy { get; set; }
        public string LocID { get; set; }
        public string SubLocID { get; set; }
        public string PackagingNo { get; set; }
        public string LotNo { get; set; }
        public string SerialNo { get; set; }
        public string BatchNo { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string PointID { get; set; }
        public string PointName { get; set; }
        public string SOID { get; set; }
        public int SOLineNum { get; set; }
        public string ShipID { get; set; }
        public int ShipLineNum { get; set; }
        public string Status { get; set; }
        public bool IsComplete { get; set; }
        public bool IsActive { get; set; }
    }
}
