//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPaymentType
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string Cate { get; set; }
        public string Name { get; set; }
        public string DRCR { get; set; }
        public string AccID { get; set; }
        public int Sort { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
