//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_StkAdjustLine
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string AdjID { get; set; }
        public int LineNum { get; set; }
        public System.DateTime AdjDate { get; set; }
        public string DocType { get; set; }
        public string LocID { get; set; }
        public string ItemID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal BeginQty { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public decimal AdjQty { get; set; }
        public decimal AdjAmt { get; set; }
        public Nullable<decimal> ActualAmt { get; set; }
        public string Unit { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
    }
}
