//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_StkAdjustHead
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string AdjID { get; set; }
        public string DocType { get; set; }
        public string Description { get; set; }
        public string LocID { get; set; }
        public string Remark { get; set; }
        public string Memo { get; set; }
        public System.DateTime AdjDate { get; set; }
        public decimal AdjQty { get; set; }
        public decimal AdjAmt { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public Nullable<decimal> ActualAmt { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
