//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_POLine
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string POID { get; set; }
        public int LineNum { get; set; }
        public string VendorID { get; set; }
        public string ToLocID { get; set; }
        public System.DateTime PODate { get; set; }
        public string OrdID { get; set; }
        public string DocType { get; set; }
        public string ItemID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal Qty { get; set; }
        public decimal ShipQty { get; set; }
        public decimal GrQty { get; set; }
        public decimal Amt { get; set; }
        public decimal ShipdAmt { get; set; }
        public decimal GrAmt { get; set; }
        public string Unit { get; set; }
        public Nullable<int> FGRefLineNum { get; set; }
        public string FGItemID { get; set; }
        public string FGName { get; set; }
        public Nullable<decimal> FGOrdQty { get; set; }
        public Nullable<decimal> FGQty { get; set; }
        public string FGUnit { get; set; }
        public bool IsActive { get; set; }
    }
}
