//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_SaleHead
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string BillID { get; set; }
        public string INVID { get; set; }
        public string FINVID { get; set; }
        public string DocTypeID { get; set; }
        public string MacNo { get; set; }
        public string MacTaxNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillRefID { get; set; }
        public string INVPeriod { get; set; }
        public string ReasonID { get; set; }
        public string TableID { get; set; }
        public string TableName { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustAccGroup { get; set; }
        public string CustTaxID { get; set; }
        public string CustBranchID { get; set; }
        public string CustBranchName { get; set; }
        public string CustAddr1 { get; set; }
        public string CustAddr2 { get; set; }
        public Nullable<bool> IsVatRegister { get; set; }
        public string POID { get; set; }
        public string ShipToLocID { get; set; }
        public string ShipToLocName { get; set; }
        public string ShipToUsePrice { get; set; }
        public string ShipToAddr1 { get; set; }
        public string ShipToAddr2 { get; set; }
        public string SalesID1 { get; set; }
        public string SalesID2 { get; set; }
        public string SalesID3 { get; set; }
        public string SalesID4 { get; set; }
        public string SalesID5 { get; set; }
        public string ContactTo { get; set; }
        public string Currency { get; set; }
        public decimal RateExchange { get; set; }
        public string RateBy { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public string CreditTermID { get; set; }
        public decimal Qty { get; set; }
        public decimal BaseNetTotalAmt { get; set; }
        public decimal NetTotalAmt { get; set; }
        public decimal NetTotalVatAmt { get; set; }
        public decimal NetTotalAmtIncVat { get; set; }
        public decimal OntopDiscPer { get; set; }
        public decimal OntopDiscAmt { get; set; }
        public decimal ItemDiscAmt { get; set; }
        public string DiscCalBy { get; set; }
        public decimal LineDisc { get; set; }
        public decimal VatRate { get; set; }
        public string VatTypeID { get; set; }
        public bool IsVatInPrice { get; set; }
        public decimal NetTotalAfterRound { get; set; }
        public decimal NetDiff { get; set; }
        public decimal PayByCash { get; set; }
        public Nullable<decimal> PayByCredit { get; set; }
        public decimal PayByOther { get; set; }
        public Nullable<decimal> PayByVoucher { get; set; }
        public decimal PayTotalAmt { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string RemarkCancel { get; set; }
        public string LocID { get; set; }
        public string SubLocID { get; set; }
        public int CountLine { get; set; }
        public int PayMethodCount { get; set; }
        public Nullable<int> CountPay { get; set; }
        public bool IsLink { get; set; }
        public string LinkBy { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public string Status { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<bool> IsRecalStock { get; set; }
        public string CreatedByApp { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
