//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public string MenuID { get; set; }
        public string TypeID { get; set; }
        public string MenuCode { get; set; }
        public string ParentID { get; set; }
        public string GroupID { get; set; }
        public int GroupSort { get; set; }
        public string SubGroupID { get; set; }
        public int SubGroupSort { get; set; }
        public string Name { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string Url { get; set; }
        public bool NeedOpenPermission { get; set; }
        public bool NeedCreatePermission { get; set; }
        public bool NeedEditPermission { get; set; }
        public bool NeedDeletePermission { get; set; }
        public bool NeedPrintPermission { get; set; }
        public bool IsActive { get; set; }
        public string CaptionOpenPermission { get; set; }
        public string CaptionCreatePermission { get; set; }
        public string CaptionEditPermission { get; set; }
        public string CaptionDeletePermission { get; set; }
        public string CaptionPrintPermission { get; set; }
        public string Icon { get; set; }
        public bool IsToggleGroupmenu { get; set; }
        public string App { get; set; }
    }
}
