//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Query
    {
        public int ID { get; set; }
        public string QueryID { get; set; }
        public string Command { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
    }
}
