//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DocTypeInfo
    {
        public string DocTypeID { get; set; }
        public string CompanyID { get; set; }
        public string ComanyName { get; set; }
        public string ApplyToComLevel { get; set; }
        public string ApplyToComLevelName { get; set; }
        public string DocTypeCode { get; set; }
        public string DocCate { get; set; }
        public string ParentID { get; set; }
        public string ParentName { get; set; }
        public string DocName { get; set; }
        public string PrefixNo { get; set; }
        public string DigitRunning { get; set; }
        public bool IsAutoID { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
