//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LocationInfo
    {
        public string LocID { get; set; }
        public string RCompany { get; set; }
        public string CompanyID { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string LocTypeID { get; set; }
        public string LocTypeName { get; set; }
        public string ParentID { get; set; }
        public string ParentName { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string XStatus { get; set; }
    }
}
