//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ORCLine
    {
        public int ID { get; set; }
        public string RCID { get; set; }
        public string CompanyID { get; set; }
        public string RCompanyID { get; set; }
        public int LineNum { get; set; }
        public string DocType { get; set; }
        public System.DateTime RCDate { get; set; }
        public string CustomerID { get; set; }
        public string SOID { get; set; }
        public string ShipID { get; set; }
        public string BillID { get; set; }
        public int PayNo { get; set; }
        public string INVID { get; set; }
        public string INVDocTypeID { get; set; }
        public System.DateTime INVDate { get; set; }
        public System.DateTime InvDueDate { get; set; }
        public decimal InvTotalAmt { get; set; }
        public decimal InvPreviousAmt { get; set; }
        public decimal PayVatAmt { get; set; }
        public decimal PayAmt { get; set; }
        public decimal PayTotalAmt { get; set; }
        public string Currency { get; set; }
        public decimal InvRateExchange { get; set; }
        public string RCStatus { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public bool IsActive { get; set; }
    }
}
