//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OINVHead
    {
        public int ID { get; set; }
        public string SOINVID { get; set; }
        public string CompanyID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyBillingID { get; set; }
        public string DocTypeID { get; set; }
        public System.DateTime SOINVDate { get; set; }
        public string CustomerID { get; set; }
        public string CustIDRefInCom { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddr1 { get; set; }
        public string CustomerAddr2 { get; set; }
        public string CustTaxID { get; set; }
        public string CustBrnID { get; set; }
        public string CustBrnName { get; set; }
        public string POID { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string RefDocID { get; set; }
        public string AccGroupID { get; set; }
        public string BillToCustomerID { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        public string ShipFrLocID { get; set; }
        public string ShipFrSubLocID { get; set; }
        public string SalesID1 { get; set; }
        public string SalesID2 { get; set; }
        public string Currency { get; set; }
        public decimal RateExchange { get; set; }
        public string RateBy { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public string TermID { get; set; }
        public Nullable<System.DateTime> PayDueDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMemo { get; set; }
        public decimal QtyOrder { get; set; }
        public decimal QtyShip { get; set; }
        public decimal QtyInvoice { get; set; }
        public decimal QtyReturn { get; set; }
        public int CountLine { get; set; }
        public decimal BaseNetTotalAmt { get; set; }
        public decimal NetTotalAmt { get; set; }
        public decimal NetTotalVatAmt { get; set; }
        public decimal NetTotalAmtIncVat { get; set; }
        public decimal ItemDiscAmt { get; set; }
        public decimal OntopDiscPer { get; set; }
        public decimal OntopDiscAmt { get; set; }
        public string DiscCalBy { get; set; }
        public decimal VatRate { get; set; }
        public string VatTypeID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public string Remark5 { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string SOID { get; set; }
        public System.DateTime SODate { get; set; }
        public string ShipID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string RCID { get; set; }
        public Nullable<System.DateTime> RCDate { get; set; }
        public string BillingID { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public int CountFCLine { get; set; }
        public string RCStatus { get; set; }
        public decimal RCAmt { get; set; }
        public decimal INVPendingAmt { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> LastStatementDate { get; set; }
        public int FCLastPayNo { get; set; }
        public int RCLastPayNo { get; set; }
        public string LastChatMessage { get; set; }
        public Nullable<System.DateTime> LastChatDate { get; set; }
        public bool IsLink { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsReverse { get; set; }
        public bool IsActive { get; set; }
    }
}
