//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PermissionInBoard
    {
        public int RN { get; set; }
        public string Username { get; set; }
        public string GroupID { get; set; }
        public string DashBoardID { get; set; }
        public string BoardName { get; set; }
        public string BoardPage { get; set; }
        public int BoardSort { get; set; }
        public string BoardUrl { get; set; }
    }
}
