//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_POS_ORDERLine
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string OrdID { get; set; }
        public int LineNum { get; set; }
        public string CustID { get; set; }
        public System.DateTime OrdDate { get; set; }
        public string DocType { get; set; }
        public string FrLocID { get; set; }
        public string ItemID { get; set; }
        public string Name { get; set; }
        public string VendorID { get; set; }
        public decimal Price { get; set; }
        public decimal OrdQty { get; set; }
        public decimal ShipQty { get; set; }
        public decimal GrQty { get; set; }
        public decimal OrdAmt { get; set; }
        public decimal ShipdAmt { get; set; }
        public decimal GrAmt { get; set; }
        public decimal BalQtyOrd { get; set; }
        public decimal BalQty { get; set; }
        public decimal OnOrdQty { get; set; }
        public string INVID { get; set; }
        public string Unit { get; set; }
        public string GrUnit { get; set; }
        public bool IsActive { get; set; }
    }
}
