//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_POS_STKMove
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string LocID { get; set; }
        public string SubLocID { get; set; }
        public string DocID { get; set; }
        public int LineNum { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string TypeID { get; set; }
        public string CateID { get; set; }
        public string LotNo { get; set; }
        public string SerialNo { get; set; }
        public string RefID { get; set; }
        public string DocType { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime StkDate { get; set; }
        public string MoveType { get; set; }
        public decimal TransQty { get; set; }
        public decimal InQty { get; set; }
        public decimal OutQty { get; set; }
        public decimal RemainQty { get; set; }
        public string Unit { get; set; }
        public decimal QtyInBaseUnit { get; set; }
        public decimal QtyInThisUnit { get; set; }
        public decimal TransQtyInBaseUnit { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
