//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PermissionGroupInMenu
    {
        public int RN { get; set; }
        public string UserGroupId { get; set; }
        public string GroupName { get; set; }
        public string MenuID { get; set; }
        public string MenuCode { get; set; }
        public string RComID { get; set; }
        public string MenuName { get; set; }
        public string GroupID { get; set; }
        public int GroupSort { get; set; }
        public string SubGroupID { get; set; }
        public int SubGroupSort { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public bool NeedOpenPermission { get; set; }
        public Nullable<bool> IsCreate { get; set; }
        public bool NeedCreatePermission { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public bool NeedEditPermission { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public bool NeedDeletePermission { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public bool NeedPrintPermission { get; set; }
        public bool IsActive { get; set; }
    }
}
