//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PermissionInMenu
    {
        public int RN { get; set; }
        public string RComID { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string TypeID { get; set; }
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuDesc1 { get; set; }
        public string MenuDesc2 { get; set; }
        public string MenuType { get; set; }
        public string MenuCode { get; set; }
        public string GroupID { get; set; }
        public int GroupSort { get; set; }
        public string SubGroupID { get; set; }
        public int SubGroupSort { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public string DataSource { get; set; }
        public string UserGroupID { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public bool NeedOpenPermission { get; set; }
        public Nullable<bool> IsCreate { get; set; }
        public bool NeedCreatePermission { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public bool NeedEditPermission { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public bool NeedDeletePermission { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public bool NeedPrintPermission { get; set; }
        public string CaptionOpenPermission { get; set; }
        public string CaptionCreatePermission { get; set; }
        public string CaptionEditPermission { get; set; }
        public string CaptionDeletePermission { get; set; }
        public string CaptionPrintPermission { get; set; }
        public bool IsToggleGroupmenu { get; set; }
        public string App { get; set; }
    }
}
