//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserInfo
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmpCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FirstName_En { get; set; }
        public string LastName_En { get; set; }
        public string FullName_En { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string DepartmentID { get; set; }
        public string PositionID { get; set; }
        public bool IsProgramUser { get; set; }
        public bool IsNewUser { get; set; }
        public string AuthenType { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string WorkAge { get; set; }
        public string AddrFull { get; set; }
        public string AddrNo { get; set; }
        public string AddrMoo { get; set; }
        public string AddrTumbon { get; set; }
        public string AddrAmphoe { get; set; }
        public string AddrProvince { get; set; }
        public string AddrPostCode { get; set; }
        public string AddrCountry { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string MaritalStatus { get; set; }
        public string CitizenId { get; set; }
        public string BookBankNumber { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<bool> UseTimeStamp { get; set; }
        public string ImageProfile { get; set; }
        public string LineToken { get; set; }
        public string DefaultCompany { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string XStatus { get; set; }
    }
}
