//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VendorInfo
    {
        public int ID { get; set; }
        public string VendorID { get; set; }
        public string VendorCode { get; set; }
        public string TypeID { get; set; }
        public string TypeName { get; set; }
        public string ParentID { get; set; }
        public string CompanyID { get; set; }
        public string ShortCode { get; set; }
        public string RefID { get; set; }
        public string TitleTh { get; set; }
        public string NameTh1 { get; set; }
        public string NameTh2 { get; set; }
        public string FullNameTh { get; set; }
        public string TitleEN { get; set; }
        public string NameEn1 { get; set; }
        public string NameEn2 { get; set; }
        public string FullNameEn { get; set; }
        public string PersonTypeID { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public string SubGroupID { get; set; }
        public string SubGroupName { get; set; }
        public string TaxID { get; set; }
        public string VatTypeID { get; set; }
        public string PaymentTermID { get; set; }
        public decimal PaymentTermValue { get; set; }
        public decimal CreditLimit { get; set; }
        public string AddrFull { get; set; }
        public string AddrNo { get; set; }
        public string AddrMoo { get; set; }
        public string AddrTumbon { get; set; }
        public string AddrAmphoe { get; set; }
        public string AddrProvince { get; set; }
        public string AddrPostCode { get; set; }
        public string AddrCountry { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        public string ContactPerson { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string AreaID { get; set; }
        public string AccGroup { get; set; }
        public string Currencry { get; set; }
        public string RateBy { get; set; }
        public string BankID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public bool IsPartner { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
    }
}
