//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XFilesRef
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string AppID { get; set; }
        public string DBServer { get; set; }
        public string DBName { get; set; }
        public string RootPathID { get; set; }
        public string FileID { get; set; }
        public string DocID { get; set; }
        public int DocLineNum { get; set; }
        public string SourceTable { get; set; }
        public string DocType { get; set; }
        public string DocCate { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public string FilePath { get; set; }
        public string SubUrl { get; set; }
        public string OriginFileName { get; set; }
        public string OriginFileExt { get; set; }
        public string OriginFilePath { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
