// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB
{
    public partial class vw_UserInGroup
    {
        public bool? IsInGroup { get; set; }
        public string Username { get; set; }
        public string RComID { get; set; }
        public string UserGroupId { get; set; }
        public string GroupName { get; set; }
        public string FullName { get; set; }
        public int GroupSort { get; set; }
        public bool IsActive { get; set; }
    }
}