// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RobotAPI.Data.DpmQDB.TT {
    public partial class DPMQContext : DbContext
    {
        private readonly IConfiguration Configuration;
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            //optionsBuilder.UseSqlServer(Configuration["GAEntities:ConnectionString"]);
            optionsBuilder.UseSqlServer(Globals.DPMQContextConn);
        }
        public DPMQContext() { }
         
        public DPMQContext(DbContextOptions<DPMQContext> options)
            : base(options) {
        }
         
        public virtual DbSet<tableau_authen> tableau_authen { get; set; }
        public virtual DbSet<tableau_board> tableau_board { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tableau_authen>(entity =>
            {
                entity.Property(e => e.api_url).HasMaxLength(300);

                entity.Property(e => e.authen_id).HasMaxLength(300);

                entity.Property(e => e.authen_name).HasMaxLength(300);

                entity.Property(e => e.password).HasMaxLength(300);

                entity.Property(e => e.username).HasMaxLength(300);
            });

            modelBuilder.Entity<tableau_board>(entity =>
            {
                entity.Property(e => e.baseurl).HasMaxLength(500);

                entity.Property(e => e.board_desc).HasMaxLength(200);

                entity.Property(e => e.board_id).HasMaxLength(50);

                entity.Property(e => e.board_name).HasMaxLength(200);

                entity.Property(e => e.board_suburl).HasMaxLength(500);

                entity.Property(e => e.display_url).HasMaxLength(500);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}