// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.DpmQDB.TT {
    public partial class tableau_board
    {
        public int id { get; set; }
        public string board_id { get; set; }
        public string board_name { get; set; }
        public string board_desc { get; set; }
        public string baseurl { get; set; }
        public string board_suburl { get; set; }
        public string display_url { get; set; }
        public int? sort { get; set; }
        public bool? is_active { get; set; }
    }
}