// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.DpmQDB.TT {
    public partial class tableau_authen
    {
        public int id { get; set; }
        public string authen_id { get; set; }
        public string authen_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string api_url { get; set; }
    }
}