// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.MainDB.TT
{
    public partial class vw_UserGroupInDocStep
    {
        public int ID { get; set; }
        public string UserGroupID { get; set; }
        public string StepID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string DocTypeID { get; set; }
        public string StepDescription { get; set; }
        public string StepName { get; set; }
        public int StepSort { get; set; }
        public bool IsActive { get; set; }
    }
}