// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace RobotWasm.Server.Data.CimsDB.TT {
    public partial class board_master
    {
        public int id { get; set; }
        public string board_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int is_active { get; set; }
    }
}