// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class Addr_Amphoe
    {
        public int ID { get; set; }
        public string AmphoeID { get; set; }
        public string AmphoeName { get; set; }
        public string ProvinceID { get; set; }
        public string CountryID { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}