// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class BankInfo
    {
        public string BankCode { get; set; }
        public string SwiftCode { get; set; }
        /// <summary>
        /// เลขที่บัญชี
        /// </summary>
        public string Name_TH { get; set; }
        /// <summary>
        /// เลขที่บัญชี
        /// </summary>
        public string Name_EN { get; set; }
        public int? Sort { get; set; }
        public bool? IsActive { get; set; }
    }
}