// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class BookBankInfo
    {
        public int ID { get; set; }
        public string BookID { get; set; }
        public string RCompanyID { get; set; }
        /// <summary>
        /// Transaction ของ KMG/KMI/ORN
        /// </summary>
        public string CompanyID { get; set; }
        /// <summary>
        /// เลขที่บัญชี
        /// </summary>
        public string BookNo { get; set; }
        /// <summary>
        /// ชื่อธนาคาร มาจาก MasterType
        /// </summary>
        public string BookDesc { get; set; }
        public string BankCode { get; set; }
        /// <summary>
        /// ชื่อธนาคาร มาจาก MasterType
        /// </summary>
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BookOwner { get; set; }
        /// <summary>
        /// 1.เงินฝากออมทรัพย์ (Saving Account)
        /// 2.เงินฝากประจำ (Fixed Deposit Account)
        /// 3.เงินฝากกระแสรายวัน (Current Account)
        /// </summary>
        public string AcctType { get; set; }
        public int Sort { get; set; }
        public string AccGroup { get; set; }
        public string AccID { get; set; }
        public string UploadTemplateID { get; set; }
        public string RefID { get; set; }
        public string Remark1 { get; set; }
        public bool? IsActive { get; set; }
    }
}