// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class CurrencyInfo
    {
        public int ID { get; set; }
        public string CurrencyID { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public int? Digit { get; set; }
        public decimal TodayRate { get; set; }
        public DateTime? DateRate { get; set; }
        public string CountryCode { get; set; }
        public string VatTypeID { get; set; }
        public bool IsActive { get; set; }
    }
}