// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class CustomerInfo
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string CustomerID { get; set; }
        public string CustCode { get; set; }
        /// <summary>
        /// HQ/BRN
        /// </summary>
        public string TypeID { get; set; }
        public string ParentID { get; set; }
        public string ShortCode { get; set; }
        public string BrnCode { get; set; }
        public string BrnDesc { get; set; }
        public string RefID { get; set; }
        public string TitleTh { get; set; }
        /// <summary>
        /// ชื่อที่ใช้ในการค้า
        /// </summary>
        public string NameTh1 { get; set; }
        /// <summary>
        /// ชื่อจดทะเบียน
        /// </summary>
        public string NameTh2 { get; set; }
        public DateTime? Birthdate { get; set; }
        public string FullNameTh { get; set; }
        public string TitleEn { get; set; }
        /// <summary>
        /// ชื่อที่ใช้ในการค้า
        /// </summary>
        public string NameEn1 { get; set; }
        /// <summary>
        /// ชื่อจดทะเบียน
        /// </summary>
        public string NameEn2 { get; set; }
        public string FullNameEn { get; set; }
        /// <summary>
        /// ประเภทบุคคล = นิติบุคคล/บุคคลธรรมดา
        /// </summary>
        public string PersonTypeID { get; set; }
        /// <summary>
        /// กลุ่มลูกค้า/ประเภทร้านค้า (TITLE) join MasterType : cust_group
        /// </summary>
        public string GroupID { get; set; }
        /// <summary>
        ///  join MasterType : cust_subgroup
        /// </summary>
        public string SubGroupID { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string ProductGroupID { get; set; }
        public string TaxID { get; set; }
        public string VatTypeID { get; set; }
        public string PaymentTermID { get; set; }
        /// <summary>
        /// NEW FOR FIN TERM
        /// </summary>
        public string InteralTermID { get; set; }
        public string PaymentGrade { get; set; }
        public decimal CreditLimit { get; set; }
        public string ContactPerson { get; set; }
        public string AddrFull { get; set; }
        /// <summary>
        /// เลขที่
        /// </summary>
        public string AddrNo { get; set; }
        public string AddrMoo { get; set; }
        /// <summary>
        /// เขต/ตำบล
        /// </summary>
        public string AddrTumbon { get; set; }
        /// <summary>
        /// แขวง/อำเภอ
        /// </summary>
        public string AddrAmphoe { get; set; }
        /// <summary>
        /// จังหวัด
        /// </summary>
        public string AddrProvince { get; set; }
        /// <summary>
        /// รหัสไปรษณีย์
        /// </summary>
        public string AddrPostCode { get; set; }
        /// <summary>
        /// ประเทศ
        /// </summary>
        public string AddrCountry { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        /// <summary>
        /// EDIT เดิม = TimeSendBill
        /// </summary>
        public string BillTime { get; set; }
        /// <summary>
        /// EDIT BillingRefDoc+BillingCondition
        /// </summary>
        public string BillMemo { get; set; }
        /// <summary>
        /// EDIT หมายเหตุการวางบิล (เดิม = Remark1)
        /// </summary>
        public string BIllPrintRemark { get; set; }
        /// <summary>
        /// EDIT เดิม = ContactPersonBill
        /// </summary>
        public string BillContact { get; set; }
        /// <summary>
        /// NEW วางบิลพร้อมส่งของ (เดิม =CanShipWithBilling)
        /// </summary>
        public bool? BillInShip { get; set; }
        /// <summary>
        /// EIDT เดิม = Remark6
        /// </summary>
        public string SOMemo { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string ChqAddr1 { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string ChqAddr2 { get; set; }
        /// <summary>
        /// NEW เดิมคือ TimeGetChq
        /// </summary>
        public string ChqTime { get; set; }
        /// <summary>
        /// EDIT หมายเหตุรับเช็ค (เดิม = Remark2)
        /// </summary>
        public string ChqPrintRemark { get; set; }
        /// <summary>
        /// EDIT เดิม = ContactPersonChq
        /// </summary>
        public string ChqContact { get; set; }
        /// <summary>
        /// EIDT ClearingCondition+ClearingRefDoc
        /// </summary>
        public string ChqMemo { get; set; }
        /// <summary>
        /// EDIT เดิม =Remark3
        /// </summary>
        public string ShipPrintRemark { get; set; }
        /// <summary>
        /// EIDT เดิม = Remark4
        /// </summary>
        public string InvPrintRemark { get; set; }
        /// <summary>
        /// NEW  เดิม = Remark5
        /// </summary>
        public string InvSignPrintRemark { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string PaymentMethod { get; set; }
        /// <summary>
        /// NEW LIMIT OVER DUE
        /// จำนวนวันที่เกิดกำหนดชำระจะต้องฟ้องศาล
        /// </summary>
        public int? LimitOverDue { get; set; }
        /// <summary>
        /// จำเป็นต้องมี Quotation ในการเปิด SO
        /// </summary>
        public bool? IsUseQO { get; set; }
        /// <summary>
        /// Tel1
        /// </summary>
        public string Tel1 { get; set; }
        /// <summary>
        /// Tel1
        /// </summary>
        public string Tel2 { get; set; }
        /// <summary>
        /// เบอร์มือถือ
        /// </summary>
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string SalePersonID { get; set; }
        public string AreaID { get; set; }
        public string BankCode { get; set; }
        public string BookIBankD { get; set; }
        public string Currency { get; set; }
        public decimal? CrmPoint { get; set; }
        public string Status { get; set; }
        public bool? IsSysData { get; set; }
        public bool IsHold { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}