// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class DashBoard
    {
        public string DashBoardID { get; set; }
        public string Name { get; set; }
        public string Page { get; set; }
        public int Sort { get; set; }
        public bool IsActive { get; set; }
    }
}