// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class IDGenerator
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string Prefix { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string MacNo { get; set; }
        public string FuncID { get; set; }
        public int DigitRunNumber { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? LatestDate { get; set; }
   
    }
}