// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class LineLogInRequest
    {
        public int ID { get; set; }
        public string ReqID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string UserType { get; set; }
        public string AppID { get; set; }
        public string LineID { get; set; }
        public string UserID { get; set; }
        public bool? HasAttachFIle { get; set; }
        /// <summary>
        /// ระบบสร้างข้อความให้ เช่น ชื่อ/ รหัสพนักงาน / Fleet 
        /// </summary>
        public string AutoDesc { get; set; }
        public string ReqMemo { get; set; }
        public DateTime RequestDate { get; set; }
        /// <summary>
        /// ACCEPTED / REJECTED / PENDING
        /// </summary>
        public string ActionStatus { get; set; }
        public string ActionBy { get; set; }
        public DateTime? ActionDate { get; set; }
        public string ActionMemo { get; set; }
        public bool IsActive { get; set; }
    }
}