// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class LineLogIn
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string FromReqID { get; set; }
        public string UserType { get; set; }
        public string AppID { get; set; }
        public string LineID { get; set; }
        public string UserID { get; set; }
        public bool? HasAttachFIle { get; set; }
        public string ReqMemo { get; set; }
        public DateTime RequestDate { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string ApprovedMemo { get; set; }
        public DateTime? LatestLogin { get; set; }
        public bool IsActive { get; set; }
    }
}