// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class MasterTypeHead
    {
        public string MasterTypeID { get; set; }
        public string UseFor { get; set; }
        public string Name { get; set; }
        /// <summary>
        /// ให้ User สามารถเพิ่มเองได้
        /// </summary>
        public bool UserAddNew { get; set; }
        public string ParentID { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}