// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class ORCAdjust
    {
        public int ID { get; set; }
        /// <summary>
        /// สาขา
        /// </summary>
        public string RCompanyID { get; set; }
        /// <summary>
        /// Transaction ของ KMG/KMI/ORN
        /// </summary>
        public string CompanyID { get; set; }
        public string RCID { get; set; }
        public int LineNum { get; set; }
        /// <summary>
        /// วันที่ขนส่ง
        /// </summary>
        public DateTime RCDate { get; set; }
        public string GLCode { get; set; }
        public string GLNam { get; set; }
        public string GLCate { get; set; }
        /// <summary>
        /// ประเภทค่าบริการ
        /// </summary>
        public int Sort { get; set; }
        public decimal CrAmt { get; set; }
        public decimal DrAmt { get; set; }
        public string Currency { get; set; }
        public decimal Rate { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public bool? IsActive { get; set; }
    }
}