// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class POS_BOMHead
    {
        public int ID { get; set; }
        public string ComID { get; set; }
        public string RComID { get; set; }
        public string BomID { get; set; }
        /// <summary>
        /// SALE
        /// </summary>
        public string UserForModule { get; set; }
        public string ItemIDFG { get; set; }
        public string Description { get; set; }
        public string Remark1 { get; set; }
        public bool IsDefault { get; set; }
        public int Priority { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}