// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class POS_Table
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        /// <summary>
        /// Company+Brn 
        /// </summary>
        public string ComID { get; set; }
        public string TableID { get; set; }
        public string TableName { get; set; }
        public int Sort { get; set; }
        public bool IsActive { get; set; }
    }
}