// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Robot.Data.GADB.TT
{
    public partial class SP_LIST_USERINCOMPANYResult
    {
        public string Username { get; set; }
        public string CompanyID { get; set; }
        public string RCompanyID { get; set; }
    }
}
