// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Robot.Data.GADB.TT
{
    public partial class SP_RptPOS134Result
    {
        public string ComID { get; set; }
        public string Company { get; set; }
        public DateTime BillDate { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public decimal Qty { get; set; }
    }
}
