// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class ThaiPostAddress
    {
        public int ID { get; set; }
        public int? PROVINCE_ID { get; set; }
        public string PROVINCE_NAME { get; set; }
        public int? BORDER_ID { get; set; }
        public string BORDER_NAME { get; set; }
        public string BORDER_POSTAL_CODE { get; set; }
        public int? DISTRICT_ID { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string DISTRICT_POSTAL_CODE { get; set; }
        public string REGION_ID { get; set; }
    }
}