// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class UserInCompany
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public bool? IsActive { get; set; }
    }
}