// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class V_Query
    {
        public int ID { get; set; }
        public string QueryID { get; set; }
        public string Command { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}