// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class VendorInfo
    {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string VendorID { get; set; }
        public string VendorCode { get; set; }
        /// <summary>
        /// HQ/BRN
        /// </summary>
        public string TypeID { get; set; }
        public string ParentID { get; set; }
        public string ShortCode { get; set; }
        public string RefID { get; set; }
        public string TitleTh { get; set; }
        /// <summary>
        /// ชื่อที่ใช้ในการค้า
        /// </summary>
        public string NameTh1 { get; set; }
        /// <summary>
        /// ชื่อจดทะเบียน
        /// </summary>
        public string NameTh2 { get; set; }
        public string FullNameTh { get; set; }
        public string TitleEn { get; set; }
        /// <summary>
        /// ชื่อที่ใช้ในการค้า
        /// </summary>
        public string NameEn1 { get; set; }
        /// <summary>
        /// ชื่อจดทะเบียน
        /// </summary>
        public string NameEn2 { get; set; }
        public string FullNameEn { get; set; }
        /// <summary>
        /// ประเภทบุคคล = นิติบุคคล/บุคคลธรรมดา
        /// </summary>
        public string PersonTypeID { get; set; }
        /// <summary>
        /// กลุ่มลูกค้า/ประเภทร้านค้า (TITLE) join MasterType : cust_group
        /// </summary>
        public string GroupID { get; set; }
        /// <summary>
        ///  join MasterType : cust_subgroup
        /// </summary>
        public string SubGroupID { get; set; }
        public string TaxID { get; set; }
        public string VatTypeID { get; set; }
        public string PaymentTermID { get; set; }
        public decimal CreditLimit { get; set; }
        public string AddrFull { get; set; }
        /// <summary>
        /// เลขที่
        /// </summary>
        public string AddrNo { get; set; }
        public string AddrMoo { get; set; }
        /// <summary>
        /// เขต/ตำบล
        /// </summary>
        public string AddrTumbon { get; set; }
        /// <summary>
        /// แขวง/อำเภอ
        /// </summary>
        public string AddrAmphoe { get; set; }
        /// <summary>
        /// จังหวัด
        /// </summary>
        public string AddrProvince { get; set; }
        /// <summary>
        /// รหัสไปรษณีย์
        /// </summary>
        public string AddrPostCode { get; set; }
        /// <summary>
        /// ประเทศ
        /// </summary>
        public string AddrCountry { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string ContactPerson { get; set; }
        /// <summary>
        /// Tel1
        /// </summary>
        public string Tel1 { get; set; }
        /// <summary>
        /// Tel1
        /// </summary>
        public string Tel2 { get; set; }
        /// <summary>
        /// เบอร์มือถือ
        /// </summary>
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string AreaID { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string AccGroup { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string Currencry { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string RateBy { get; set; }
        /// <summary>
        /// NEW
        /// </summary>
        public string BankID { get; set; }
        public string BankCode { get; set; }
        public bool? IsPartner { get; set; }
        /// <summary>
        /// หมายเหตุการวางบิล
        /// </summary>
        public string Remark1 { get; set; }
        /// <summary>
        /// หมายเหตุรับเช็ค
        /// </summary>
        public string Remark2 { get; set; }
        /// <summary>
        /// หมาย เอกสารแนบท้ายการแจ้งส่ง
        /// </summary>
        public string Remark3 { get; set; }
        /// <summary>
        /// หมายเหตุท้ายอินวอยซ์
        /// </summary>
        public string Remark4 { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Status { get; set; }
        public bool? IsActive { get; set; }
    }
}