// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class vw_ORCLine
    {
        public int ID { get; set; }
        public string RCID { get; set; }
        public string CompanyID { get; set; }
        public string RCompanyID { get; set; }
        public int LineNum { get; set; }
        public string DocType { get; set; }
        public DateTime RCDate { get; set; }
        public string CustomerID { get; set; }
        public string SOID { get; set; }
        public string ShipID { get; set; }
        public string BillID { get; set; }
        public int PayNo { get; set; }
        public string INVID { get; set; }
        public string INVDocTypeID { get; set; }
        public DateTime INVDate { get; set; }
        public DateTime InvDueDate { get; set; }
        public decimal InvTotalAmt { get; set; }
        public decimal InvPreviousAmt { get; set; }
        public decimal PayVatAmt { get; set; }
        public decimal PayAmt { get; set; }
        public decimal PayTotalAmt { get; set; }
        public string Currency { get; set; }
        public decimal InvRateExchange { get; set; }
        public string RCStatus { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public bool IsActive { get; set; }
    }
}