// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class vw_POS_ORDERHead
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string ComName { get; set; }
        public string OrdID { get; set; }
        public string DocType { get; set; }
        public string FrLocID { get; set; }
        public string Description { get; set; }
        public string Remark1 { get; set; }
        public string AcceptedMemo { get; set; }
        public DateTime OrdDate { get; set; }
        public decimal OrdQty { get; set; }
        public decimal OrdAmt { get; set; }
        public string AcceptedBy { get; set; }
        public DateTime? AcceptedDate { get; set; }
        public string ShipBy { get; set; }
        public DateTime? ShipDate { get; set; }
        public decimal ShipQty { get; set; }
        public decimal ShipdAmt { get; set; }
        public string GRBy { get; set; }
        public DateTime? GRDate { get; set; }
        public decimal GrAmt { get; set; }
        public decimal GrQty { get; set; }
        public string Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}