// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class vw_POS_ORDER_RM
    {
        public string DocType { get; set; }
        public DateTime OrdDate { get; set; }
        public string VendorID { get; set; }
        public string RmItemID { get; set; }
        public string RmItemName { get; set; }
        public string RComID { get; set; }
        public decimal? RmQty { get; set; }
        public decimal? RmAmt { get; set; }
    }
}