// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Robot.Data.GADB.TT
{
    public partial class vw_UserInRCom
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string RComName { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
    }
}