// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class board_in_user
    {
        public int id { get; set; }
        /// <summary>
        /// รหัส Dashboard
        /// </summary>
        public string board_id { get; set; }
        /// <summary>
        /// ชื่อผู้ใช้งาน
        /// </summary>
        public string username { get; set; }
        public string layout_json { get; set; }
        public int sort { get; set; }
    }
}