// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class custom_widget_master
    {
        public int id { get; set; }
        public string widget_id { get; set; }
        public string widget_desc { get; set; }
        public int? h_colspan { get; set; }
        public int? h_rowspan { get; set; }
        public int? v_colspan { get; set; }
        public int? v_rowspan { get; set; }
        public int? v_sort { get; set; }
        public int? h_sort { get; set; }
        public string? group_id { get; set; }
        public string? group_name { get; set; }
        public int? is_active { get; set; }
    }
}