// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class dqt_data_logs
    {
        public Guid log_id { get; set; }
        /// <summary>
        /// GUID for each job run
        /// </summary>
        public string job_id { get; set; }
        /// <summary>
        /// รหัสชุดข้อมูล
        /// </summary>
        public string data_set_id { get; set; }
        /// <summary>
        /// วันที่ job run
        /// </summary>
        public DateOnly? job_date { get; set; }
        /// <summary>
        /// เวลา job run
        /// </summary>
        public TimeOnly? job_time { get; set; }
        /// <summary>
        /// success / warning /error
        /// </summary>
        public string job_result { get; set; }
        /// <summary>
        /// ข้อความจาก job
        /// </summary>
        public string job_message { get; set; }
        /// <summary>
        /// ชื่อไฟล์นำเข้า
        /// </summary>
        public string filename { get; set; }
    }
}