// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class dss_earthquake
    {
        public string earthquake_key { get; set; }
        public DateTime? earthquake_date { get; set; }
        public decimal? earthquake_mag { get; set; }
        public decimal? earthquake_lat { get; set; }
        public decimal? earthquake_long { get; set; }
        public decimal? earthquake_depth { get; set; }
        public string earthquake_region { get; set; }
        public DateTime? earthquake_timestamp { get; set; }
        public string earthquake_source { get; set; }
        public string status_land { get; set; }
        public decimal? distance_th { get; set; }
        public string status_inth { get; set; }
    }
}