// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace RobotAPI.Data.CimsDB.TT {
    public partial class dss_rain
    {
        public Guid? id { get; set; }
        public string station_id { get; set; }
        public string station_name { get; set; }
        public DateTime? data_date { get; set; }
        public decimal? rn_24h { get; set; }
        public DateTime? rn_timestamp { get; set; }
    }
}