// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class dss_water
    {
        public Guid? id { get; set; }
        public string station_id { get; set; }
        public DateTime? h_date { get; set; }
        public decimal? waterline_lv { get; set; }
        public decimal? waterline_vol { get; set; }
        public DateTime? h_timestamp { get; set; }
    }
}