// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class dss_rid_dam
    {
        public Guid? id { get; set; }
        public string station_id { get; set; }
        public DateTime? wd_date { get; set; }
        public string station_name { get; set; }
        public string dam_type { get; set; }
        public decimal? lat { get; set; }
        public decimal? lng { get; set; }
        public string project_name { get; set; }
        public string province { get; set; }
        public string region { get; set; }
        public decimal? cap_resv { get; set; }
        public decimal? low_qdisc { get; set; }
        public decimal? qdisc_prev { get; set; }
        public decimal? perc_resv_prev { get; set; }
        public decimal? qdisc_curr { get; set; }
        public decimal? perc_resv_curr { get; set; }
        public decimal? jan_info { get; set; }
        public decimal? q_info { get; set; }
        public decimal? q_outfo { get; set; }
        public decimal? water_workable { get; set; }
        public DateTime? wd_timestamp { get; set; }
    }
}