// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.DataStoreDB.TT {
    public partial class est_stock_cms
    {
        public decimal? stock_id { get; set; }
        public DateTime? stock_date { get; set; }
        public decimal? stockdoc_item_id { get; set; }
        public decimal? stuff_id { get; set; }
        public decimal? stuff_id_parent { get; set; }
        public string stuff_code { get; set; }
        public string stuff_name { get; set; }
        public decimal? stuff_price { get; set; }
        public decimal? count_in { get; set; }
        public decimal? count_out { get; set; }
        public decimal? create_user { get; set; }
        public DateTime? create_time { get; set; }
        public decimal? is_clear { get; set; }
        public decimal? locate_id { get; set; }
        public string locate_name { get; set; }
        public string province_name { get; set; }
        public string department_name { get; set; }
        public DateTime? etl_date { get; set; }
    }
}