// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class mas_province
    {
        public int id { get; set; }
        public string province_id { get; set; }
        public string province_name { get; set; }
        public string country { get; set; }
        public string created_by { get; set; }
        public DateTime? created_date { get; set; }
        public bool? isactive { get; set; }
    }
}