// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class nda_aws_weather
    {
        public Guid weather_id { get; set; }
        public string station_id { get; set; }
        public string location_name { get; set; }
        public decimal? lat { get; set; }
        public decimal? lon { get; set; }
        public string aws_serial_name { get; set; }
        public DateTime? aws_rec_time { get; set; }
        public decimal? aws_battery_volt { get; set; }
        public decimal? aws_ptemp { get; set; }
        public decimal? aws_pressure { get; set; }
        public decimal? aws_rainfall { get; set; }
        public decimal? aws_temperature { get; set; }
        public decimal? aws_relatvie_humidity { get; set; }
        public decimal? aws_wind_speed { get; set; }
        public decimal? aws_wind_direction { get; set; }
        public string aws_active_status { get; set; }
        public DateTime? aws_last_update { get; set; }
        public string aq_serial_name { get; set; }
        public DateTime? aq_record_time { get; set; }
        public decimal? aq_temperature { get; set; }
        public decimal? aq_dew_point { get; set; }
        public decimal? aq_no2 { get; set; }
        public decimal? aq_o3 { get; set; }
        public decimal? aq_ox { get; set; }
        public decimal? aq_relative_humidity { get; set; }
        public decimal? aq_pm1 { get; set; }
        public decimal? aq_pm25 { get; set; }
        public decimal? aq_pm10 { get; set; }
        public decimal? aq_tsp { get; set; }
        public string aq_active_status { get; set; }
        public DateTime? aq_last_update { get; set; }
        public decimal? acc_rainfall_3hours { get; set; }
        public decimal? acc_rainfall_24hours { get; set; }
        public DateTime? acc_rainfall_lastupdate { get; set; }
        public DateTime? acc_rainfall_rec_time { get; set; }
        public string region { get; set; }
        public string province_name { get; set; }
        public string pid { get; set; }
        public string amphoe_name { get; set; }
        public string aid { get; set; }
        public string tambon_name { get; set; }
        public string tid { get; set; }
    }
}