// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class vw_board_in_user
    {
        public int? id { get; set; }
        public string board_id { get; set; }
        public string board_name { get; set; }
        public string board_description { get; set; }
        public int? sort { get; set; }
        public string board_type { get; set; }
        public string username { get; set; }
        public string layout_json_h { get; set; }
        public string layout_json_v { get; set; }
        public string board_url { get; set; }
        public string authen_name { get; set; }
        public string board_username { get; set; }
        public string board_pass { get; set; }
        public string base_url { get; set; }
        public int? is_active { get; set; }
    }
}