// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotAPI.Data.CimsDB.TT {
    public partial class vw_custom_board_in_user
    {
        public int? id { get; set; }
        public string username { get; set; }
        public string? user_fullname { get; set; }
        public string board_type { get; set; }
        public string board_id { get; set; }
        public string board_name { get; set; }
        public string board_desc { get; set; }
        public int? is_active { get; set; }
    }
}