// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace RobotWasm.Shared.Data.DimsDB {
    public partial class api_tag {
        public int id { get; set; }
        public string tag { get; set; }
        public string api_id { get; set; }
        public int is_active { get; set; }
    }
}