// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB
{
    public partial class usergroup_in_api
    {
        public int id { get; set; }
        public string group_id { get; set; }
        public string api_id { get; set; }
    }
}