// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class usermenu {
        public int id { get; set; }
        public string menu_id { get; set; }
        public string menu_code { get; set; }
        public string menu_name { get; set; }
        public string menu_description1 { get; set; }
        public string menu_description2 { get; set; }
        public int? is_open { get; set; }
        public int? is_create { get; set; }
        public int? is_edit { get; set; }
        public int? is_print { get; set; }
        public int? is_delete { get; set; }
        public int? need_open { get; set; }
        public int? need_create { get; set; }
        public int? need_edit { get; set; }
        public int? need_print { get; set; }
        public int? need_delete { get; set; }
        public string? text_open { get; set; }
        public string? text_create { get; set; }
        public string? text_edit { get; set; }
        public string? text_print { get; set; }

        public string? text_delete { get; set; }
        public string icon { get; set; }
        public string url { get; set; }
        public int? is_active { get; set; }
        public string type_id { get; set; }
        public string group_id { get; set; }
        public string app_id { get; set; }
        public int? group_sort { get; set; }
        public int? menu_sort { get; set; }

    }
}