// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.DimsDB {
    public partial class xfile_location
    {
        public int id { get; set; }
        public string rootpath_id { get; set; }
        public string rooturl { get; set; }
        public string rooturl_public { get; set; }
        public string root_path { get; set; }
        public string appid { get; set; }
        public string dbserver { get; set; }
        public string dbname { get; set; }
        public string login_name { get; set; }
        public string login_pass { get; set; }
        public string created_by { get; set; }
        public DateTime? created_date { get; set; }
        public DateTime? start_date { get; set; }
        public DateTime? end_date { get; set; }
        public string jwttoken { get; set; }
   public int? is_current { get; set; }
        public DateTime? jwttoken_expirydate { get; set; }
        public string? jwt_refresh_token { get; set; }
        public int? is_active { get; set; }
    }
}