// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiGateWay.Data.CimsDB {
    public partial class api_log
    {
        public int id { get; set; }
        public string username { get; set; }
        public string api_id { get; set; }
        public string req_url { get; set; }
        public DateTime? req_time { get; set; }
    }
}