// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiGateWay.Data.CimsDB {
    public partial class api_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string token { get; set; }
        public DateTime? latest_login { get; set; }
        public string role { get; set; }
        public DateTime? created_date { get; set; }
        public int? isactive { get; set; }
    }
}