//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF.Data.GADB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OMS_Entities : DbContext
    {
        public OMS_Entities()
            : base("name=OMS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerInfo> CustomerInfo { get; set; }
        public virtual DbSet<ItemInfo> ItemInfo { get; set; }
        public virtual DbSet<OSOHead> OSOHead { get; set; }
        public virtual DbSet<OSOLine> OSOLine { get; set; }
        public virtual DbSet<OSOLot> OSOLot { get; set; }
        public virtual DbSet<STKBal> STKBal { get; set; }
        public virtual DbSet<STKItemBal> STKItemBal { get; set; }
        public virtual DbSet<STKMove> STKMove { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<vw_OSOHead> vw_OSOHead { get; set; }
        public virtual DbSet<vw_OSOLine> vw_OSOLine { get; set; }
        public virtual DbSet<vw_OSOLot> vw_OSOLot { get; set; }
        public virtual DbSet<LocationInfo> LocationInfo { get; set; }
        public virtual DbSet<UserInRCom> UserInRCom { get; set; }
        public virtual DbSet<UserInGroup> UserInGroup { get; set; }
    
        public virtual int sp_ResetStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ResetStock");
        }
    }
}
