//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF.Data.GADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OSOHead
    {
        public int ID { get; set; }
        public string OrdID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public System.DateTime OrdDate { get; set; }
        public string DocTypeID { get; set; }
        public string DocTypeName { get; set; }
        public string INVID { get; set; }
        public Nullable<System.DateTime> INVDate { get; set; }
        public string CustID { get; set; }
        public string CustName { get; set; }
        public string CustAddr1 { get; set; }
        public string CustAddr2 { get; set; }
        public string CustTaxID { get; set; }
        public string CustBrnID { get; set; }
        public string CustBrnName { get; set; }
        public string CustMobile { get; set; }
        public string CustEmail { get; set; }
        public string BrandID { get; set; }
        public string DepID { get; set; }
        public string AreaID { get; set; }
        public string PaymentTermID { get; set; }
        public string DeliveryBy { get; set; }
        public string POID { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string RefDocID { get; set; }
        public string AccGroupID { get; set; }
        public string BillToCustID { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        public string ShipFrLocID { get; set; }
        public string ShipFrSubLocID { get; set; }
        public string SalesID1 { get; set; }
        public string SalesName { get; set; }
        public string SalesID2 { get; set; }
        public string Currency { get; set; }
        public decimal RateExchange { get; set; }
        public string RateBy { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public string TermID { get; set; }
        public Nullable<System.DateTime> PayDueDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMemo { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyShip { get; set; }
        public decimal QtyInvoice { get; set; }
        public decimal QtyReturn { get; set; }
        public decimal QtyShipPending { get; set; }
        public decimal QtyInvoicePending { get; set; }
        public decimal AmtShipPending { get; set; }
        public decimal AmtInvoice { get; set; }
        public decimal AmtInvoicePending { get; set; }
        public int CountLine { get; set; }
        public decimal BaseNetTotalAmt { get; set; }
        public decimal BaseNetTotalAmtIncVat { get; set; }
        public decimal NetTotalAmt { get; set; }
        public decimal NetTotalVatAmt { get; set; }
        public decimal NetTotalAmtIncVat { get; set; }
        public decimal ItemDiscAmt { get; set; }
        public Nullable<decimal> ItemDiscAmtIncVat { get; set; }
        public decimal OntopDiscPer { get; set; }
        public decimal OntopDiscAmt { get; set; }
        public decimal OntopDiscAmtIncVat { get; set; }
        public string DiscCalBy { get; set; }
        public decimal VatRate { get; set; }
        public string VatTypeID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string TName { get; set; }
        public string AName { get; set; }
        public string PName { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string ShipID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public bool IsLink { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public string DiscStatus { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
        public string Status { get; set; }
        public string Source { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
