// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB
{
    public class POS_Table {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string TableID { get; set; }
        public string TableName { get; set; }
        public int Sort { get; set; }
        public bool IsActive { get; set; }
    }



}