// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB
{
    public class vw_ItemInfo {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string ItemID { get; set; }
        public string ItemCode { get; set; }
        public string MasterItemID { get; set; }
        public string GLGroupID { get; set; }
        public string RefID { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Barcode { get; set; }
        public string NameDisplay { get; set; }
        public string TypeID { get; set; }
        public string TypeName { get; set; }
        public string CateID { get; set; }
        public string CateName { get; set; }
        public string Group1ID { get; set; }
        public string Group1Name { get; set; }
        public string Group2ID { get; set; }
        public string Group2Name { get; set; }
        public string Group3ID { get; set; }
        public string Group3Name { get; set; }
        public string BrandID { get; set; }
        public string BrandName { get; set; }
        public string SerialNumber { get; set; }
        public bool IsPackaging { get; set; }
        public string PackagingID { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public string PriceTaxCondType { get; set; }
        public string UnitID { get; set; }
        public string StkUnitID { get; set; }
        public decimal VolPerUOM { get; set; }
        public string VendorID { get; set; }
        public decimal Weight { get; set; }
        public decimal Dimension { get; set; }
        public string VatTypeID { get; set; }
        public string VatTypeName { get; set; }
        public bool IsKeepStock { get; set; }
        public bool IsLotItem { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public int? Sort { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool IsHold { get; set; }
        public string Status { get; set; }
        public bool IsSysData { get; set; }
        public bool IsActive { get; set; }
    }
}