// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB
{
    public partial class vw_PermissionInBoard
    {
        public int RN { get; set; }
        public string Username { get; set; }
        public string GroupID { get; set; }
        public string DashBoardID { get; set; }
        public string BoardName { get; set; }
        public string BoardPage { get; set; }
        public string BoardUrl { get; set; }
        public int BoardSort { get; set; }
    }
}