// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB
{
    public partial class vw_UserInDocStep
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string StepID { get; set; }
        public string DocTypeID { get; set; }
        public string StepDescription { get; set; }
        public string StepName { get; set; }
        public int StepSort { get; set; }
        public bool IsActive { get; set; }
    }
}