// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public partial class Addr_District
    {
        public int ID { get; set; }
        public string ProvinceID { get; set; }
        public string ProvinceIDEng { get; set; }
        public string AmphoeID { get; set; }
        public string AmphoeIDEng { get; set; }
        public string DistrictID { get; set; }
        public string DistrictIDEng { get; set; }
        public string PostCode { get; set; }
        public string CountryID { get; set; }
        public string RegionID { get; set; }
        public bool? IsMetropolis { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}