// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public partial class Link
    {
        public int Id { get; set; }
        public string LinkType { get; set; }
        public string LinkName { get; set; }
        public string BaseUrl { get; set; }
        public string AppLink { get; set; }
        public string Port { get; set; }
        public string VirtualPath { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string Token { get; set; }
        public string Domain { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string AuthenType { get; set; }
        public string Description { get; set; }
        public int? Sort { get; set; }
        public bool? IsActive { get; set; }
    }
}