// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public class StkAdjustLine {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string AdjID { get; set; }
        public int LineNum { get; set; }
        public DateTime AdjDate { get; set; }
        public string DocType { get; set; }
        public string LocID { get; set; }
        public string ItemID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal BeginQty { get; set; }
        public decimal? ActualQty { get; set; }
        public decimal AdjQty { get; set; }
        public decimal AdjAmt { get; set; }
        public decimal? ActualAmt { get; set; }
        public string Unit { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
    }
}