// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public class StkTransferHead {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string ComID { get; set; }
        public string TRID { get; set; }
        public string? BrandID { get; set; }
        public string DocType { get; set; }
        public string Description { get; set; }
        public string LocIDFr { get; set; }
        public string LocIDTo { get; set; }
        public string Remark { get; set; }
        public string Memo { get; set; }
        public DateTime TRDate { get; set; }
        public decimal Qty { get; set; }
        public decimal Amt { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime ApprovedDate { get; set; }
        public string Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }


}