// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public partial class UserGroupInfo
    {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string UserGroupID { get; set; }
        public string GroupName { get; set; }
        public int Sort { get; set; }
        public string LineToken { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? IsActive { get; set; }
    }
}