// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public class UserInLoc {
        public int ID { get; set; }
        public string RComID { get; set; }
        public string UserName { get; set; }
        public string LocID { get; set; }
        public bool IsActive { get; set; }
    }

}