// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Data.GADB.TT
{
    public class vw_PromotionItem {
        public int ID { get; set; }
        public string RCompanyID { get; set; }
        public string CompanyID { get; set; }
        public string ProID { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string BrandID { get; set; }
        public string CateID { get; set; }
        public decimal PriceIncVat { get; set; }
        public decimal PriceProIncVat { get; set; }
        public string PatternID { get; set; }
        public bool IsActive { get; set; }
    }

}