//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintMaster.Data.PrintDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintData
    {
        public int ID { get; set; }
        public string PrintID { get; set; }
        public string FormPrintID { get; set; }
        public string JsonData { get; set; } 
        public System.DateTime PrintDate { get; set; }
        public string AppID { get; set; }
    }
}
