// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RobotWasm.Shared.Data.GaDB {
    public partial class OSOLine
    {
        public int ID { get; set; }
        /// <summary>
        /// สาขา
        /// </summary>
        public string RComID { get; set; }
        /// <summary>
        /// Transaction ของ KMG/KMI/ORN
        /// </summary>
        public string ComID { get; set; }
        public string OrdID { get; set; }
        public int LineNum { get; set; }
        /// <summary>
        /// ServiceID FROM TABLE OrderServices
        /// </summary>
        public string DocTypeID { get; set; }
        public DateTime OrdDate { get; set; }
        public string INVID { get; set; }
        /// <summary>
        /// วันที่ขนส่ง
        /// </summary>
        public DateTime? INVDate { get; set; }
        public string RefDocID { get; set; }
        public int RefDocLineNum { get; set; }
        public string CustID { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemTypeID { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemCateID { get; set; }
        public string ItemGroupID { get; set; }
        public string ItemAccGroupID { get; set; }
        public bool? IsStockItem { get; set; }
        public decimal Weight { get; set; }
        public string WUnit { get; set; }
        /// <summary>
        /// จำนวน Order รวม
        /// </summary>
        public decimal Qty { get; set; }
        /// <summary>
        /// จำนวน Order รวม
        /// </summary>
        public decimal QtyShip { get; set; }
        /// <summary>
        /// จำนวน Order รวม
        /// </summary>
        public decimal QtyInvoice { get; set; }
        /// <summary>
        /// จำนวน Order รวม
        /// </summary>
        public decimal QtyShipPending { get; set; }
        /// <summary>
        /// จำนวน Order รวม
        /// </summary>
        public decimal QtyInvoicePending { get; set; }
        public decimal AmtShipPending { get; set; }
        public decimal AmtInvoicePending { get; set; }
        public string Unit { get; set; }
        /// <summary>
        /// CANCEL
        /// </summary>
        public string Packaging { get; set; }
        public decimal Price { get; set; }
        public decimal PriceIncVat { get; set; }
        /// <summary>
        /// ราคาสุทธิก่อนส่วนลด
        /// </summary>
        public decimal BaseTotalAmt { get; set; }
        public decimal BaseTotalAmtIncVat { get; set; }
        public decimal TotalAmt { get; set; }
        public decimal VatAmt { get; set; }
        public decimal TotalAmtIncVat { get; set; }
        public decimal VatRate { get; set; }
        public string VatTypeID { get; set; }
        /// <summary>
        /// มูลค่าส่วนลดท้ายบิล
        /// </summary>
        public decimal OntopDiscAmt { get; set; }
        /// <summary>
        /// เปอร์เซ็นต์ส่วนลดท้ายบิล
        /// </summary>
        public decimal OntopDiscPer { get; set; }
        public decimal OntopDiscAmtIncVat { get; set; }
        public decimal DiscPer { get; set; }
        public decimal DiscAmt { get; set; }
        public decimal DiscAmtIncVat { get; set; }
        public string DiscCalBy { get; set; }
        public decimal DiscPPU { get; set; }
        public decimal DiscPPUIncVat { get; set; }
        /// <summary>
        /// Location in ACCPAC
        /// </summary>
        public string LocID { get; set; }
        public string SubLocID { get; set; }
        public string PackagingNo { get; set; }
        public string LotNo { get; set; }
        public string SerialNo { get; set; }
        public string BatchNo { get; set; }
        public bool? IsSpecialPrice { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        /// <summary>
        /// NONE / WEIGHT / DIRECT
        /// </summary>
        public string PointID { get; set; }
        /// <summary>
        /// NONE / WEIGHT / DIRECT
        /// </summary>
        public string PointName { get; set; }
        public string ShipID { get; set; }
  
        /// <summary>
        /// วันที่ขนส่ง
        /// </summary>
        public int ShipLineNum { get; set; }
        public string? DiscApproveBy { get; set; }
        public DateTime? DiscApproveDate { get; set; }
        public string Status { get; set; }
        public bool IsComplete { get; set; }
        public int? Sort { get; set; }
		public string? ProID { get; set; }
        public string? ProName { get; set; }
        public string? PatternID { get; set; }
		public bool? PageBreak { get; set; }
        public bool? IsActive { get; set; }
    }
}